"""add book language and paperback

Revision ID: 538b15cbeada
Revises: 7dd84d6c4dd4
Create Date: 2023-10-22 14:09:41.201631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538b15cbeada'
down_revision = '7dd84d6c4dd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('books', sa.Column('paperback', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_books_language'), 'books', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_language'), table_name='books')
    op.drop_column('books', 'paperback')
    op.drop_column('books', 'language')
    # ### end Alembic commands ###
