"""initial

Revision ID: 6503572691b4
Revises: 
Create Date: 2023-03-22 01:39:00.984664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6503572691b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamerevocationaudits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('audit_category', sa.String(length=128), nullable=True),
    sa.Column('publisher', sa.String(length=512), nullable=True),
    sa.Column('operator', sa.String(length=512), nullable=True),
    sa.Column('revocation_msg', sa.String(length=2048), nullable=True),
    sa.Column('audit_no', sa.String(length=128), nullable=True),
    sa.Column('isbn', sa.String(length=128), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamerevocationaudits_id'), 'gamerevocationaudits', ['id'], unique=False)
    op.create_table('gamealterationaudits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('audit_category', sa.String(length=128), nullable=True),
    sa.Column('publisher', sa.String(length=512), nullable=True),
    sa.Column('operator', sa.String(length=512), nullable=True),
    sa.Column('alteration_msg', sa.String(length=2048), nullable=True),
    sa.Column('audit_no', sa.String(length=128), nullable=True),
    sa.Column('isbn', sa.String(length=128), nullable=True),
    sa.Column('alter_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamealterationaudits_id'), 'gamealterationaudits', ['id'], unique=False)
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_table('egameaudits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('publisher', sa.String(length=512), nullable=True),
    sa.Column('audit_no', sa.String(length=128), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_egameaudits_audit_no'), 'egameaudits', ['audit_no'], unique=False)
    op.create_index(op.f('ix_egameaudits_id'), 'egameaudits', ['id'], unique=False)
    op.create_index(op.f('ix_egameaudits_publisher'), 'egameaudits', ['publisher'], unique=False)
    op.create_table('networkgameaudits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('audit_category', sa.String(length=128), nullable=True),
    sa.Column('publisher', sa.String(length=512), nullable=True),
    sa.Column('operator', sa.String(length=512), nullable=True),
    sa.Column('audit_no', sa.String(length=128), nullable=True),
    sa.Column('isbn', sa.String(length=128), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networkgameaudits_id'), 'networkgameaudits', ['id'], unique=False)
    op.create_table('gameaudits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gameaudits_id'), 'gameaudits', ['id'], unique=False)
    op.create_index(op.f('ix_gameaudits_title'), 'gameaudits', ['title'], unique=True)
    op.create_index(op.f('ix_gameaudits_url'), 'gameaudits', ['url'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('publish_date', sa.String(length=10), nullable=True),
    sa.Column('cover_img', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_description'), 'books', ['description'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_description'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_gameaudits_url'), table_name='gameaudits')
    op.drop_index(op.f('ix_gameaudits_title'), table_name='gameaudits')
    op.drop_index(op.f('ix_gameaudits_id'), table_name='gameaudits')
    op.drop_table('gameaudits')
    op.drop_index(op.f('ix_networkgameaudits_id'), table_name='networkgameaudits')
    op.drop_table('networkgameaudits')
    op.drop_index(op.f('ix_egameaudits_publisher'), table_name='egameaudits')
    op.drop_index(op.f('ix_egameaudits_id'), table_name='egameaudits')
    op.drop_index(op.f('ix_egameaudits_audit_no'), table_name='egameaudits')
    op.drop_table('egameaudits')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_gameauditchanges_id'), table_name='gameauditchanges')
    op.drop_table('gamealterationaudits')
    op.drop_index(op.f('ix_gamerevocationaudits_id'), table_name='gamerevocationaudits')
    op.drop_table('gamerevocationaudits')
    # ### end Alembic commands ###
