"""update book descrpition

Revision ID: 7dd84d6c4dd4
Revises: 6503572691b4
Create Date: 2023-10-22 13:57:14.814340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dd84d6c4dd4'
down_revision = '6503572691b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('description_index', table_name='books')
    op.alter_column('books', 'description',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('description_index', 'books', ['description'], unique=False)
    op.alter_column('books', 'description',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###
