"""add NPPA table

Revision ID: 848bcc86a451
Revises: ce6b60fbd794
Create Date: 2023-03-21 02:18:51.994083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848bcc86a451'
down_revision = 'ce6b60fbd794'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nppatables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nppatables_id'), 'nppatables', ['id'], unique=False)
    op.create_index(op.f('ix_nppatables_title'), 'nppatables', ['title'], unique=True)
    op.create_index(op.f('ix_nppatables_url'), 'nppatables', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nppatables_url'), table_name='nppatables')
    op.drop_index(op.f('ix_nppatables_title'), table_name='nppatables')
    op.drop_index(op.f('ix_nppatables_id'), table_name='nppatables')
    op.drop_table('nppatables')
    # ### end Alembic commands ###
